stages:
  map:
    cmd: python -m data.mapping_classes
    deps:
    - data/mapping_classes.py
    - data/raw
    outs:
    - data/processed
  subset:
    cmd: python -m data.create_random_subset
    deps:
    - data/create_random_subset.py
    - data/processed
    outs:
    - data/processed_subset
